### PR TITLE
Fixed issue where running "cd" would give the user a "command not found" message

### LINKED ISSUE #9: "change dir (cd)" commands returns error but still does its magic
Moving directories returns error though successfull.

example

`c:\website-terminal\ : `
`c:\website-terminal\ : cd testdir`

> path "testdir" not found

`c:\website-terminal\testdir : `

### PR DESCRIPTION
**Pull request by Samyocord**
Fixes #9

### CODE REVIEW

File: commands/log.php [hunk 1]
```diff
@@ -35,6 +35,8 @@ function terminal_input(String $inputquery, String $rootPath): void
         // Dont run empty inputs
         if (strlen($inputquery ) < 2)
             return;
+		if (substr($inputquery, 0, 3) === "cd ")
+			return;
```
Comment (PatricNox) [inline commands/log.php:39]: Instead of nested if conditions, you can write it like so:

```
 if (strlen($inputquery ) < 2 || substr($inputquery, 0, 3) === "cd "))
            return;
```

Also, I can't immediately see how this fixes the problem without causing new bugs, so I'll have to test this once the refactoring is done. :)
